import { TextField } from './TextField';
import type { Meta, StoryObj } from '@storybook/react';

const meta = {
  title: 'Components/TextField',
  component: TextField,
  tags: ['autodocs'],
  args: {
    ariaLabelledby: undefined,
    autoComplete: 'off',
    children: '',
    disabled: false,
    error: false,
    id: 'example-id',
    inputMode: 'text',
    name: 'example-name',
    required: false,
    type: 'text',
    value: '',
    width: 'auto',
  },
  argTypes: {
    ariaLabelledby: { control: 'text' },
    autoComplete: {
      control: 'select',
      options: [
        'additional-name',
        'address-level1',
        'address-level2',
        'address-level3',
        'address-level4',
        'address-line1',
        'address-line2',
        'address-line3',
        'bday-day',
        'bday-month',
        'bday-year',
        'bday',
        'cc-additional-name',
        'cc-csc',
        'cc-exp-month',
        'cc-exp-year',
        'cc-exp',
        'cc-family-name',
        'cc-given-name',
        'cc-name',
        'cc-number',
        'cc-type',
        'country-name',
        'country',
        'current-password',
        'current-password webauthn',
        'email',
        'family-name',
        'given-name',
        'honorific-prefix',
        'honorific-suffix',
        'impp',
        'language',
        'name',
        'new-password',
        'nickname',
        'off',
        'on',
        'one-time-code',
        'organization-title',
        'organization',
        'photo',
        'postal-code',
        'sex',
        'street-address',
        'tel-area-code',
        'tel-country-code',
        'tel-extension',
        'tel-local-prefix',
        'tel-local-suffix',
        'tel-local',
        'tel-national',
        'tel',
        'transaction-amount',
        'transaction-currency',
        'url',
        'username',
        'username webauthn',
      ],
    },
    children: { control: 'text' },
    disabled: { control: 'boolean' },
    error: { control: 'boolean' },
    id: { control: 'text' },
    inputMode: {
      control: 'select',
      options: [
        'none',
        'text',
        'tel',
        'url',
        'email',
        'numeric',
        'decimal',
        'search',
      ],
    },
    name: { control: 'text' },
    required: { control: 'boolean' },
    rows: { control: 'number' },
    type: {
      control: 'select',
      options: ['text', 'email', 'password', 'number', 'tel'],
    },
    value: { control: 'text' },
    width: {
      control: 'select',
      options: ['auto', 'full', 'half', 'third'],
    },
  },
} satisfies Meta<typeof TextField>;

export default meta;
type Story = StoryObj<typeof meta>;

export const InteractiveDemo: Story = {};

export const multipleLine: Story = {
  args: { rows: 4 },
};
